### ISSUE TITLE
Error 65531

### ISSUE THREAD

**Issue by clarkd** [ThomasTavernier/node-broadlink#1]
Hi,

I'm running the following but getting error 65531, any ideas?

```
    const devices = await broadlink.discover();
    const device = devices[0];
    const auth = await device.auth();
    
    const freqs = await device.sweepFrequency();
    console.log(freqs);
   
    const packet = await device.findRfPacket();
```

Thanks!

**Comment by ThomasTavernier** [comment]
Oh, didn't receive an email, sorry, hi.

Well, since the broadlinks devices are shittier than I expected, I didn't use it that much.
It can either be an broadlink error or an issue with this lib.
Checking the [python-broadlink](http://github.com/mjg59/python-broadlink) may (or could have :/) help you.

**Comment by stephenmcd1** [comment]
I'm hitting this as well, did you figure anything out @clarkd ?

**Comment by ThomasTavernier** [comment]
I got this error with my RM Mini 3, device that does not support RF (so frequency methods shouldn't be available in my case).

Does your device support those?

**Comment by stephenmcd1** [comment]
I get that error code when using the `sendData` function actually.  I'm using an RM Mini3 and have been able to use that same sendData function with a .net library so my device should support it.

**Comment by ThomasTavernier** [comment]
I'm in the process of updating and re-synchronizing with the pyton package, I'll aim to add tests for each case based on python result as well, but it'll take some more time.
If you can provide me your device.devtype, I'll try to verify your case before that.
